### ISSUE TITLE
Get People updated since...

### ISSUE THREAD

**Issue by jemcguire** [planningcenter/pco_api_oauth_example_sinatra_ruby#2]
Is there a way to query the API to pull everyone people/v2/people that have been updated since 6/12/2017?  I've been using https://api.planningcenteronline.com/people/v2/people?where[updated_at]=2017-06-12 but it isn't bringing anyone back.  Thanks in advance.
john

**Comment by seven1m** [comment]
@jemcguire sorry I didn't notice this issue. You probably already figured this out, but just for posterity, the query you're looking for is this:

https://api.planningcenteronline.com/people/v2/people?where[updated_at][gte]=2017-06-12
